# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chat.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x04\x63hat\"%\n\x07Message\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"\x1d\n\nMessageAck\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x07\n\x05\x45mpty2n\n\x0b\x43hatService\x12.\n\x0bSendMessage\x12\r.chat.Message\x1a\x10.chat.MessageAck\x12/\n\x0fReceiveMessages\x12\x0b.chat.Empty\x1a\r.chat.Message0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGE']._serialized_start=20
  _globals['_MESSAGE']._serialized_end=57
  _globals['_MESSAGEACK']._serialized_start=59
  _globals['_MESSAGEACK']._serialized_end=88
  _globals['_EMPTY']._serialized_start=90
  _globals['_EMPTY']._serialized_end=97
  _globals['_CHATSERVICE']._serialized_start=99
  _globals['_CHATSERVICE']._serialized_end=209
# @@protoc_insertion_point(module_scope)
